import { Language } from '../types';

export const getStampPresets = (language: Language) => {
    const isKuOrAr = language === 'ku' || language === 'ar';
    
    return [
      {
        // 1. Classic Company Seal (Standard dual ring, stars)
        id: 'company',
        nameKey: 'stamp.template.company',
        shape: 'circle' as const,
        width: 40,
        height: 40,
        outerText: isKuOrAr ? 'کۆمپانیای عەشتار بۆ بازرگانی گشتی' : 'ASHTAR COMPANY FOR GENERAL TRADE',
        innerText: isKuOrAr ? 'عێراق - بەغداد - هەولێر' : 'IRAQ - BAGHDAD - ERBIL',
        centerText: isKuOrAr ? 'پەسەندکرا' : 'APPROVED',
        textColor: '#1e3a8a',
        borderWidth: 4,
        fontFamily: 'Inter',
        outerFontFamily: 'Inter',
        innerFontFamily: 'Inter',
        centerFontFamily: 'Inter',
        fontSize: 38,
        outerFontSize: 38,
        innerFontSize: 38,
        centerFontSize: 42,
        outerRadiusOffset: 0,
        innerRadiusOffset: 0,
        hasInnerRing: true,
        hasDottedRing: false,
        hasStars: true,
        starCount: 2,
        distressEffect: 0,
        letterSpacing: 2,
        centerImageSize: 55,
        centerLayout: 'text-bottom',
        centerImageOffsetX: 0,
        centerImageOffsetY: 0,
        centerTextOffsetX: 0,
        centerTextOffsetY: 0, outerTextOffsetX: 0, outerTextOffsetY: 0, innerTextOffsetX: 0, innerTextOffsetY: 0, extraCenterText: '', extraCenterFontFamily: 'Noto Naskh Arabic', extraCenterFontSize: 24, extraCenterTextOffsetX: 0, extraCenterTextOffsetY: 0
      },
      {
        // 2. Official Ministry / Government (Dotted ring, Center star)
        id: 'ministry',
        nameKey: 'stamp.template.ministry',
        shape: 'circle' as const,
        width: 45,
        height: 45,
        outerText: isKuOrAr ? 'کۆماری عێراق - وەزارەتی پەروەردە' : 'REPUBLIC OF IRAQ - MINISTRY OF EDUCATION',
        innerText: isKuOrAr ? 'بەڕێوبەرایەتی گشتی چاپی کتێب' : 'GENERAL DIRECTORATE OF PRINTING',
        centerText: '★',
        textColor: '#16a34a',
        borderWidth: 5,
        fontFamily: 'Inter',
        outerFontFamily: 'Inter',
        innerFontFamily: 'Inter',
        centerFontFamily: 'Inter',
        fontSize: 42,
        outerFontSize: 42,
        innerFontSize: 40,
        centerFontSize: 48,
        outerRadiusOffset: 0,
        innerRadiusOffset: 0,
        hasInnerRing: true,
        hasDottedRing: true,
        hasStars: false,
        starCount: 0,
        distressEffect: 0,
        letterSpacing: 1,
        centerImageSize: 55,
        centerLayout: 'text-bottom',
        centerImageOffsetX: 0,
        centerImageOffsetY: 0,
        centerTextOffsetX: 0,
        centerTextOffsetY: 0, outerTextOffsetX: 0, outerTextOffsetY: 0, innerTextOffsetX: 0, innerTextOffsetY: 0, extraCenterText: '', extraCenterFontFamily: 'Noto Naskh Arabic', extraCenterFontSize: 24, extraCenterTextOffsetX: 0, extraCenterTextOffsetY: 0
      },
      {
        // 3. Bank / Paid Oval (Oval, stars, double text)
        id: 'bank',
        nameKey: 'stamp.template.bank',
        shape: 'oval' as const,
        width: 55,
        height: 35,
        outerText: isKuOrAr ? 'بانکی نیشتمانیی عێراق - لقی سەرەکی' : 'IRAQ NATIONAL BANK - MAIN BRANCH',
        innerText: isKuOrAr ? 'بەشی دارایی و وەبەرهێنان' : 'FINANCIAL & INVESTMENT DEPT',
        centerText: isKuOrAr ? 'درا / PAID' : 'PAID',
        textColor: '#6b21a8',
        borderWidth: 4,
        fontFamily: 'Inter',
        outerFontFamily: 'Inter',
        innerFontFamily: 'Inter',
        centerFontFamily: 'Inter',
        fontSize: 36,
        outerFontSize: 36,
        innerFontSize: 34,
        centerFontSize: 44,
        outerRadiusOffset: 0,
        innerRadiusOffset: 0,
        hasInnerRing: true,
        hasDottedRing: false,
        hasStars: true,
        starCount: 2,
        distressEffect: 0,
        letterSpacing: 1.5,
        centerImageSize: 55,
        centerLayout: 'text-bottom',
        centerImageOffsetX: 0,
        centerImageOffsetY: 0,
        centerTextOffsetX: 0,
        centerTextOffsetY: 0, outerTextOffsetX: 0, outerTextOffsetY: 0, innerTextOffsetX: 0, innerTextOffsetY: 0, extraCenterText: '', extraCenterFontFamily: 'Noto Naskh Arabic', extraCenterFontSize: 24, extraCenterTextOffsetX: 0, extraCenterTextOffsetY: 0
      },
      {
        // 4. Quality Control Box (Thick border rectangle, no text other than center)
        id: 'qc_passed',
        nameKey: 'stamp.template.approved', // Reusing translation
        shape: 'rectangle' as const,
        width: 55,
        height: 25,
        outerText: '',
        innerText: '',
        centerText: isKuOrAr ? 'دەرچووە\nQC PASSED' : 'QC PASSED',
        textColor: '#dc2626',
        borderWidth: 8,
        fontFamily: 'Inter',
        outerFontFamily: 'Inter',
        innerFontFamily: 'Inter',
        centerFontFamily: 'Inter',
        fontSize: 48,
        outerFontSize: 38,
        innerFontSize: 38,
        centerFontSize: 52,
        outerRadiusOffset: 0,
        innerRadiusOffset: 0,
        hasInnerRing: false,
        hasDottedRing: false,
        hasStars: false,
        starCount: 0,
        distressEffect: 0,
        letterSpacing: 4,
        centerImageSize: 55,
        centerLayout: 'text-bottom',
        centerImageOffsetX: 0,
        centerImageOffsetY: 0,
        centerTextOffsetX: 0,
        centerTextOffsetY: 0, outerTextOffsetX: 0, outerTextOffsetY: 0, innerTextOffsetX: 0, innerTextOffsetY: 0, extraCenterText: '', extraCenterFontFamily: 'Noto Naskh Arabic', extraCenterFontSize: 24, extraCenterTextOffsetX: 0, extraCenterTextOffsetY: 0
      },
      {
        // 5. Minimalist Monogram / Logo Stand-in (Circle, large center letter, no rings)
        id: 'monogram',
        nameKey: 'stamp.template.engineer',
        shape: 'circle' as const,
        width: 35,
        height: 35,
        outerText: '',
        innerText: '',
        centerText: 'A',
        textColor: '#000000',
        borderWidth: 5,
        fontFamily: 'Inter',
        outerFontFamily: 'Inter',
        innerFontFamily: 'Inter',
        centerFontFamily: 'Inter',
        fontSize: 34,
        outerFontSize: 34,
        innerFontSize: 34,
        centerFontSize: 90,
        outerRadiusOffset: 0,
        innerRadiusOffset: 0,
        hasInnerRing: false,
        hasDottedRing: false,
        hasStars: false,
        starCount: 0,
        distressEffect: 0,
        letterSpacing: 0,
        centerImageSize: 55,
        centerLayout: 'text-bottom',
        centerImageOffsetX: 0,
        centerImageOffsetY: 0,
        centerTextOffsetX: 0,
        centerTextOffsetY: 0, outerTextOffsetX: 0, outerTextOffsetY: 0, innerTextOffsetX: 0, innerTextOffsetY: 0, extraCenterText: '', extraCenterFontFamily: 'Noto Naskh Arabic', extraCenterFontSize: 24, extraCenterTextOffsetX: 0, extraCenterTextOffsetY: 0
      },
      {
        // 6. Confidential Warning (Square, thick, dotted inner)
        id: 'confidential',
        nameKey: 'stamp.template.paid', // Reusing paid or similar
        shape: 'square' as const,
        width: 45,
        height: 45,
        outerText: '',
        innerText: '',
        centerText: isKuOrAr ? 'نهێنی\nCONFIDENTIAL' : 'CONFIDENTIAL',
        textColor: '#dc2626',
        borderWidth: 6,
        fontFamily: 'Inter',
        outerFontFamily: 'Inter',
        innerFontFamily: 'Inter',
        centerFontFamily: 'Inter',
        fontSize: 32,
        outerFontSize: 32,
        innerFontSize: 32,
        centerFontSize: 36,
        outerRadiusOffset: 0,
        innerRadiusOffset: 0,
        hasInnerRing: true,
        hasDottedRing: true,
        hasStars: false,
        starCount: 0,
        distressEffect: 0,
        letterSpacing: 1,
        centerImageSize: 55,
        centerLayout: 'text-bottom',
        centerImageOffsetX: 0,
        centerImageOffsetY: 0,
        centerTextOffsetX: 0,
        centerTextOffsetY: 0, outerTextOffsetX: 0, outerTextOffsetY: 0, innerTextOffsetX: 0, innerTextOffsetY: 0, extraCenterText: '', extraCenterFontFamily: 'Noto Naskh Arabic', extraCenterFontSize: 24, extraCenterTextOffsetX: 0, extraCenterTextOffsetY: 0
      },
      {
        // 7. Signature Line (Rectangle, very wide, lines)
        id: 'signature',
        nameKey: 'stamp.template.signature',
        shape: 'rectangle' as const,
        width: 70,
        height: 25,
        outerText: '',
        innerText: '',
        centerText: isKuOrAr ? 'واژۆ\n.........................' : 'SIGNATURE\n.........................',
        textColor: '#000000',
        borderWidth: 2,
        fontFamily: 'Inter',
        outerFontFamily: 'Inter',
        innerFontFamily: 'Inter',
        centerFontFamily: 'Inter',
        fontSize: 32,
        outerFontSize: 32,
        innerFontSize: 32,
        centerFontSize: 36,
        outerRadiusOffset: 0,
        innerRadiusOffset: 0,
        hasInnerRing: false,
        hasDottedRing: false,
        hasStars: false,
        starCount: 0,
        distressEffect: 0,
        letterSpacing: 2,
        centerImageSize: 55,
        centerLayout: 'text-bottom',
        centerImageOffsetX: 0,
        centerImageOffsetY: 0,
        centerTextOffsetX: 0,
        centerTextOffsetY: 0, outerTextOffsetX: 0, outerTextOffsetY: 0, innerTextOffsetX: 0, innerTextOffsetY: 0, extraCenterText: '', extraCenterFontFamily: 'Noto Naskh Arabic', extraCenterFontSize: 24, extraCenterTextOffsetX: 0, extraCenterTextOffsetY: 0
      },
      {
        // 8. Certified True Copy (Oval, huge letter spacing, multiple stars)
        id: 'certified',
        nameKey: 'stamp.template.received',
        shape: 'oval' as const,
        width: 60,
        height: 45,
        outerText: isKuOrAr ? 'وێنەیەکی ڕاستەقینەی پەسەندکراو' : 'CERTIFIED TRUE COPY',
        innerText: isKuOrAr ? 'بەڕێوەبەرایەتی یاسایی' : 'LEGAL DEPARTMENT',
        centerText: '✓',
        textColor: '#1e3a8a',
        borderWidth: 3,
        fontFamily: 'Inter',
        outerFontFamily: 'Inter',
        innerFontFamily: 'Inter',
        centerFontFamily: 'Inter',
        fontSize: 38,
        outerFontSize: 38,
        innerFontSize: 38,
        centerFontSize: 50,
        outerRadiusOffset: -5,
        innerRadiusOffset: -5,
        hasInnerRing: true,
        hasDottedRing: false,
        hasStars: true,
        starCount: 4,
        distressEffect: 0,
        letterSpacing: 3,
        centerImageSize: 55,
        centerLayout: 'text-bottom',
        centerImageOffsetX: 0,
        centerImageOffsetY: 0,
        centerTextOffsetX: 0,
        centerTextOffsetY: 0, outerTextOffsetX: 0, outerTextOffsetY: 0, innerTextOffsetX: 0, innerTextOffsetY: 0, extraCenterText: '', extraCenterFontFamily: 'Noto Naskh Arabic', extraCenterFontSize: 24, extraCenterTextOffsetX: 0, extraCenterTextOffsetY: 0
      }
    ];
};
